const standardVaccines = [
  { name: "Hepatitis B", ageMonths: 0, description: "First dose at birth" },
  { name: "Hepatitis B", ageMonths: 1, description: "Second dose" },
  { name: "DTaP", ageMonths: 2, description: "Diphtheria, Tetanus, Pertussis" },
  { name: "Hib", ageMonths: 2, description: "Haemophilus influenzae type b" },
  { name: "PCV", ageMonths: 2, description: "Pneumococcal conjugate" },
  { name: "IPV", ageMonths: 2, description: "Inactivated poliovirus" },
  { name: "Rotavirus", ageMonths: 2, description: "Oral rotavirus vaccine" },
  { name: "DTaP", ageMonths: 4, description: "Second dose" },
  { name: "Hib", ageMonths: 4, description: "Second dose" },
  { name: "PCV", ageMonths: 4, description: "Second dose" },
  { name: "IPV", ageMonths: 4, description: "Second dose" },
  { name: "Rotavirus", ageMonths: 4, description: "Second dose" },
  { name: "Hepatitis B", ageMonths: 6, description: "Third dose" },
  { name: "DTaP", ageMonths: 6, description: "Third dose" },
  { name: "Hib", ageMonths: 6, description: "Third dose" },
  { name: "PCV", ageMonths: 6, description: "Third dose" },
  { name: "IPV", ageMonths: 6, description: "Third dose" },
  { name: "Rotavirus", ageMonths: 6, description: "Third dose" },
  { name: "Influenza", ageMonths: 6, description: "Annual flu vaccine" },
  { name: "MMR", ageMonths: 12, description: "Measles, Mumps, Rubella" },
  { name: "Varicella", ageMonths: 12, description: "Chickenpox vaccine" },
  { name: "Hepatitis A", ageMonths: 12, description: "First dose" },
  { name: "PCV", ageMonths: 15, description: "Booster dose" },
  { name: "Hib", ageMonths: 15, description: "Booster dose" },
  { name: "DTaP", ageMonths: 18, description: "Fourth dose" },
  { name: "Hepatitis A", ageMonths: 18, description: "Second dose (6 months after first)" },
  { name: "IPV", ageMonths: 4*12, description: "Booster dose (age 4-6 years)" },
  { name: "MMR", ageMonths: 4*12, description: "Second dose (age 4-6 years)" },
  { name: "Varicella", ageMonths: 4*12, description: "Second dose (age 4-6 years)" },
  { name: "DTaP", ageMonths: 11*12, description: "Tdap booster (age 11-12 years)" },
  { name: "HPV", ageMonths: 11*12, description: "Human Papillomavirus (2-3 dose series)" },
  { name: "Meningococcal", ageMonths: 11*12, description: "First dose (age 11-12 years)" },
  { name: "Meningococcal", ageMonths: 16*12, description: "Booster dose (age 16 years)" }
];
export default standardVaccines;